# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArchitectureProposal-V1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArchitectureProposal-V1
  pod 'Alamofire',    '~> 4.4'
  pod 'RealmSwift',   '~> 2.8.3'
  pod 'RxRealm',      '~> 0.6.0'
  pod 'SwiftyJSON'
  pod 'Swifter',      '~> 1.3.3'
  pod 'Valet',        '~> 2.4.0'
  pod 'Firebase/Core'
  pod 'RxCocoa',      '~> 3.6.0'


  target 'ArchitectureProposal-V1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArchitectureProposal-V1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
